### ISSUE TITLE
Issues with Gryffin during pip install summit

### ISSUE THREAD

**Issue by ddceruti** [sustainable-processes/summit#102]
Hi Summit team!
I am trying to install the package through pip and cannot get it to work.
* Operating System:
Windows 10 (10.0.18363)
* Python version:
Python 3.7.10 through anaconda
* summit version used:
current summit version on pypi (0.6.0). Made sure that no pip cache dir was used to reproduce a clean installation.
### Description
I want to use summit for some benchmarking. My intention is to emulate the experiments you provide to test my optimization package and ideally compare that to the strategies you implemented. I would appreciate some help with the installation!

1. 
When installing it, gryffin produces an error which makes the installation fail:
```pip install summit --no-cache-dir```

```
WARNING: Discarding https://files.pythonhosted.org/packages/04/f5/72388bf9ae2289f6c6c6c464243a5fb2ebd0d235e897bf144e1c6c0abcba/gryffin-0.1.1.tar.gz#sha256=ef44cf79616e078406c5ba5cedfc95d1919673fc0f8f13abb18ea3567c06e47d (from https://pypi.org/simple/gryffin/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
It then tries to find a previous version of summit and it fails again:
```
ERROR: Could not find a version that satisfies the requirement gryffin<0.2.0,>=0.1.1 (from summit)
ERROR: No matching distribution found for gryffin<0.2.0,>=0.1.1
```

2. 
Tried to install the "stopgap" branch of issue #71 and could also not get it to work with
'''pip install git+https://github.com/sustainable-processes/summit.git@stopgap#egg=summit --no-cache-dir'''
which produces:

```
ERROR: Cannot install summit and summit==0.6.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    summit 0.6.0 depends on torch<2.0.0 and >=1.4.0
    blitz-bayesian-pytorch 0.2.3 depends on torch==1.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
3. 
I tried to force torch==1.4.0 through the command above with 
'''pip install git+https://github.com/sustainable-processes/summit.git@stopgap#egg=summit --no-cache-dir torch==1.4.0"
'''
Which produces
```
ERROR: Could not find a version that satisfies the requirement torch==1.4.0
ERROR: No matching distribution found for torch==1.4.0
```

### What I Did
I set up a new environment for summit with "conda install python=3.7"
then activated it and ran "pip install summit".
```bash
(summit_stopgap) C:\Users\dede\Documents\work\MA\code\olympus>pip install summit --no-cache-dir
Collecting summit
  Downloading summit-0.6.0-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 1.3 MB/s
Collecting GPy<2.0,>=1.9
  Downloading GPy-1.9.9-cp37-cp37m-win_amd64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 1.3 MB/s
Collecting pandas<2.0.0,>=1.1.0
  Downloading pandas-1.2.3-cp37-cp37m-win_amd64.whl (9.1 MB)
     |████████████████████████████████| 9.1 MB 2.2 MB/s
Collecting matplotlib<4.0.0,>=3.2.2
  Downloading matplotlib-3.3.4-cp37-cp37m-win_amd64.whl (8.5 MB)
     |████████████████████████████████| 8.5 MB 1.6 MB/s
Collecting pymoo<0.5.0,>=0.4.1
  Downloading pymoo-0.4.2.2-cp37-cp37m-win_amd64.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 3.3 MB/s
Collecting pyrff<2.0.0,>=1.0.1
  Downloading pyrff-1.0.1-py3-none-any.whl (24 kB)
Collecting ipywidgets<8.0.0,>=7.5.1
  Downloading ipywidgets-7.6.3-py2.py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 2.2 MB/s
Collecting SQSnobFit<0.5.0,>=0.4.3
  Downloading SQSnobFit-0.4.5.tar.gz (29 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting torch<2.0.0,>=1.4.0
  Downloading torch-1.8.0-cp37-cp37m-win_amd64.whl (190.5 MB)
     |████████████████████████████████| 190.5 MB 2.2 MB/s
Collecting gryffin<0.2.0,>=0.1.1
  Downloading gryffin-0.1.1.tar.gz (586 kB)
     |████████████████████████████████| 586 kB 504 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\dede\miniconda3\envs\summit_stopgap\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dede\\AppData\\Local\\Temp\\pip-install-l06tumu5\\gryffin_4c3a824b2cd84b5d8d8755fdf9d17aec\\setup.py'"'"'; __file__='"'"'C:\\Users\\dede\\AppData\\Local\\Temp\\pip-install-l06tumu5\\gryffin_4c3a824b2cd84b5d8d8755fdf9d17aec\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dede\AppData\Local\Temp\pip-pip-egg-info-b2gyo0hb'
         cwd: C:\Users\dede\AppData\Local\Temp\pip-install-l06tumu5\gryffin_4c3a824b2cd84b5d8d8755fdf9d17aec\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dede\AppData\Local\Temp\pip-install-l06tumu5\gryffin_4c3a824b2cd84b5d8d8755fdf9d17aec\setup.py", line 50, in <module>
        packages=find_packages('./src/'),
      File "C:\Users\dede\miniconda3\envs\summit_stopgap\lib\site-packages\setuptools\__init__.py", line 64, in find
        convert_path(where),
      File "C:\Users\dede\miniconda3\envs\summit_stopgap\lib\distutils\util.py", line 112, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path './src/' cannot end with '/'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/04/f5/72388bf9ae2289f6c6c6c464243a5fb2ebd0d235e897bf144e1c6c0abcba/gryffin-0.1.1.tar.gz#sha256=ef44cf79616e078406c5ba5cedfc95d1919673fc0f8f13abb18ea3567c06e47d (from https://pypi.org/simple/gryffin/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Collecting summit
  Downloading summit-0.5.0-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 6.4 MB/s
Collecting tensorflow<3.0.0,>=2.2.0
  Downloading tensorflow-2.4.1-cp37-cp37m-win_amd64.whl (370.7 MB)
     |████████████████████████████████| 370.7 MB 2.2 MB/s
Collecting tensorflow-estimator<2.3.0,>=2.2.0
  Downloading tensorflow_estimator-2.2.0-py2.py3-none-any.whl (454 kB)
     |████████████████████████████████| 454 kB 3.2 MB/s
Collecting tensorflow-probability<0.11.0,>=0.10.1
  Downloading tensorflow_probability-0.10.1-py2.py3-none-any.whl (3.5 MB)
     |████████████████████████████████| 3.5 MB 6.4 MB/s
Collecting numpy==1.18.0
  Downloading numpy-1.18.0-cp37-cp37m-win_amd64.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB 3.3 MB/s
Collecting gpyopt<2.0.0,>=1.2.6
  Downloading GPyOpt-1.2.6.tar.gz (56 kB)
     |████████████████████████████████| 56 kB 3.8 MB/s
Collecting blitz-bayesian-pytorch==0.2.3
  Downloading blitz_bayesian_pytorch-0.2.3-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 3.2 MB/s
Collecting fastprogress<0.3.0,>=0.2.3
  Downloading fastprogress-0.2.6-py3-none-any.whl (12 kB)
Collecting torchvision==0.5.0
  Downloading torchvision-0.5.0-cp37-cp37m-win_amd64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 3.3 MB/s
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of summit to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement gryffin<0.2.0,>=0.1.1 (from summit)
ERROR: No matching distribution found for gryffin<0.2.0,>=0.1.1

(summit_stopgap) C:\Users\dede\Documents\work\MA\code\olympus>pip install git+https://github.com/sustainable-processes/summit.git@stopgap#egg=summit --no-cache-dir
Collecting summit
  Cloning https://github.com/sustainable-processes/summit.git (to revision stopgap) to c:\users\dede\appdata\local\temp\pip-install-dvhj63zk\summit_5ad513dcd7434d2f860024e926e3ef0b
  Running command git clone -q https://github.com/sustainable-processes/summit.git 'C:\Users\dede\AppData\Local\Temp\pip-install-dvhj63zk\summit_5ad513dcd7434d2f860024e926e3ef0b'
  Running command git checkout -b stopgap --track origin/stopgap
  Branch 'stopgap' set up to track remote branch 'stopgap' from 'origin'.
  Switched to a new branch 'stopgap'
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting fastprogress<0.3.0,>=0.2.3
  Downloading fastprogress-0.2.6-py3-none-any.whl (12 kB)
Collecting blitz-bayesian-pytorch==0.2.3
  Downloading blitz_bayesian_pytorch-0.2.3-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 1.1 MB/s
Collecting ipywidgets<8.0.0,>=7.5.1
  Downloading ipywidgets-7.6.3-py2.py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 3.3 MB/s
Collecting numpy==1.18.0
  Downloading numpy-1.18.0-cp37-cp37m-win_amd64.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB 6.4 MB/s
Collecting torch<2.0.0,>=1.4.0
  Downloading torch-1.8.0-cp37-cp37m-win_amd64.whl (190.5 MB)
     |████████████████████████████████| 190.5 MB 1.1 MB/s
Collecting GPy<2.0,>=1.9
  Downloading GPy-1.9.9-cp37-cp37m-win_amd64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 2.2 MB/s
Collecting pymoo<0.5.0,>=0.4.1
  Downloading pymoo-0.4.2.2-cp37-cp37m-win_amd64.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 6.8 MB/s
Collecting matplotlib<4.0.0,>=3.2.2
  Downloading matplotlib-3.3.4-cp37-cp37m-win_amd64.whl (8.5 MB)
     |████████████████████████████████| 8.5 MB 6.8 MB/s
Collecting SQSnobFit<0.5.0,>=0.4.3
  Downloading SQSnobFit-0.4.5.tar.gz (29 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pandas<2.0.0,>=1.1.0
  Downloading pandas-1.2.3-cp37-cp37m-win_amd64.whl (9.1 MB)
     |████████████████████████████████| 9.1 MB 6.4 MB/s
Collecting gpyopt<2.0.0,>=1.2.6
  Downloading GPyOpt-1.2.6.tar.gz (56 kB)
     |████████████████████████████████| 56 kB ...
Collecting tensorflow<3.0.0,>=2.3.0
  Downloading tensorflow-2.4.1-cp37-cp37m-win_amd64.whl (370.7 MB)
     |████████████████████████████████| 370.7 MB 6.4 MB/s
Collecting pyrff<2.0.0,>=1.0.1
  Downloading pyrff-1.0.1-py3-none-any.whl (24 kB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of summit to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install summit and summit==0.6.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    summit 0.6.0 depends on torch<2.0.0 and >=1.4.0
    blitz-bayesian-pytorch 0.2.3 depends on torch==1.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

(summit_stopgap) C:\Users\dede\Documents\work\MA\code\olympus>pip install git+https://github.com/sustainable-processes/summit.git@stopgap#egg=summit --no-cache-dir torch==1.4.0
Collecting summit
  Cloning https://github.com/sustainable-processes/summit.git (to revision stopgap) to c:\users\dede\appdata\local\temp\pip-install-l6a7mbkw\summit_f529d1dec68a4c14a8c31a064bcaa724
  Running command git clone -q https://github.com/sustainable-processes/summit.git 'C:\Users\dede\AppData\Local\Temp\pip-install-l6a7mbkw\summit_f529d1dec68a4c14a8c31a064bcaa724'
  Running command git checkout -b stopgap --track origin/stopgap
  Branch 'stopgap' set up to track remote branch 'stopgap' from 'origin'.
  Switched to a new branch 'stopgap'
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Could not find a version that satisfies the requirement torch==1.4.0
ERROR: No matching distribution found for torch==1.4.0
```

**Comment by ddceruti** [comment]
I read Issue #71 again and resoved the problem by building from git instead. Sorry for any inconveniences! Here is the command which successfully built the package:
'''pip install git+https://github.com/sustainable-processes/summit.git@v0.8.0#egg=summit --no-cache-dir'''

**Comment by marcosfelt** [comment]
Thanks Andreo for posting this. As you noted, the pre-release 0.8.0rc1
fixes these issues. The official release should be out soon.
