### ISSUE TITLE
Issue with TSEMO >= 3 previous results

### ISSUE THREAD

**Issue by jarw2** [sustainable-processes/summit#152]
* Operating System: WSL 2 Ubuntu 20.04
* Python version: Python 3.8.10
* summit version used: 0.8.3

### Description

Predict next experiments using TSEMO using 6 initial previous results. Worked fine for SNOBFIT and SOBO.
Note that TSEMO works fine for <=3 initial previous results. I checked and I have the version of summit including this modification " Fix bug in hypervolume calculation for d>=3 (#151) ".

### What I Did
TSEMOtest.py:
```python

from summit.domain import *
from summit.strategies import TSEMO
from summit.utils.dataset import DataSet
import pandas as pd
import numpy as np

#create domain of dependent variables and objective functions
domain = Domain()
domain += ContinuousVariable(name='c13', description='conc.  of 13, ester alkyne, [M]', bounds=[0, 5])
domain += ContinuousVariable(name='c2', description='conc. of 2, DCPD, [M]', bounds=[0, 5])
domain += ContinuousVariable(name='P', description='pressure [bar]', bounds=[0, 20])
domain += ContinuousVariable(name="conv", description='relative conversion to 14', bounds=[0,100], is_objective=True, maximize=True)

#create dictionary with experimental results
d = {'c13': [2.5,2.5,2.5,2.0,1.0,0.5], 'c2': [1.2,3.0,1.5,2.0,1.0,0.5], 'P': [5.3,4,5,9,9,9], 'conv': [52,39,51,92,88,82]}
#create pandas dataframe from dictionary
df = pd.DataFrame(data=d)

initial = DataSet.from_df(df)
print(initial)

strategy = TSEMO(domain)

#Run TSEMO to suggest 5 next experiments to perform
next_experiments = strategy.suggest_experiments(5, initial)

print(next_experiments)
```
"

bash:
```bash

/usr/bin/python3 /home/jarw2/Chalmers/TSEMOtest.py
NAME  c13   c2    P  conv
TYPE DATA DATA DATA  DATA
0     2.5  1.2  5.3  52.0
1     2.5  3.0  4.0  39.0
2     2.5  1.5  5.0  51.0
3     2.0  2.0  9.0  92.0
4     1.0  1.0  9.0  88.0
5     0.5  0.5  9.0  82.0
Traceback (most recent call last):
  File "/home/jarw2/Chalmers/TSEMOtest.py", line 30, in <module>
    next_experiments = strategy.suggest_experiments(5, initial)
  File "/home/jarw2/.local/lib/python3.8/site-packages/summit/strategies/tsemo.py", line 248, in suggest_experiments
    self.hv_imp, indices = self._select_max_hvi(outputs, y, num_experiments)
  File "/home/jarw2/.local/lib/python3.8/site-packages/summit/strategies/tsemo.py", line 469, in _select_max_hvi
    masked_index = np.argmax(hv_improvement)
  File "<__array_function__ internals>", line 5, in argmax
  File "/home/jarw2/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1195, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/home/jarw2/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence

```

**Comment by marcosfelt** [comment]
I will take a look at this later today.

**Comment by marcosfelt** [comment]
Sorry for the delay. The issue is that TSEMO is a multiobjective strategy and you are working only one objective. Consider using SOBO or STBO instead.
