### ISSUE TITLE
Example in Readme throwing an error

### ISSUE THREAD

**Issue by ilario** [sustainable-processes/summit#201]
* Operating System: Arch Linux
* Python version: 3.10.6
* summit version used: 0.8.7

### Description

I installed the latest version of Summit and run the example listing taken from the Readme file.
I got the error message reported below.
It is not clear at all which threshold I should increase.

### What I Did

´´´
$ python -m venv .venv
$ ~ source .venv/bin/activate
$ ~ pip install -U summit
python
Python 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from summit.benchmarks import SnarBenchmark
>>> from summit.strategies import NelderMead, MultitoSingleObjective
>>> from summit.run import Runner
>>> 
>>> exp = SnarBenchmark()
>>> 
>>> transform = MultitoSingleObjective(
...     exp.domain, expression="-sty/1e4+e_factor/100", maximize=False
... )
>>> 
>>> nm = NelderMead(exp.domain, transform=transform)
>>> 
>>> r = Runner(
...     strategy=nm, experiment=exp,max_iterations=50
... )
>>> r.run()

/home/ilario/.venv/lib/python3.10/site-packages/summit/strategies/neldermead.py:195: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  next_experiments = next_experiments.drop(("constraint", "DATA"), 1)
/home/ilario/.venv/lib/python3.10/site-packages/summit/experiment.py:92: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._data = self._data.append(res)
/home/ilario/.venv/lib/python3.10/site-packages/summit/strategies/neldermead.py:146: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  invalid_res = self.prev_param[1].drop(("constraint", "DATA"), 1)
[... many many more FutureWarning messages ...]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ilario/.venv/lib/python3.10/site-packages/summit/run.py", line 164, in run
    next_experiments = self.strategy.suggest_experiments(
  File "/home/ilario/.venv/lib/python3.10/site-packages/summit/strategies/neldermead.py", line 159, in suggest_experiments
    next_experiments, xbest, fbest, param = self._inner_suggest_experiments(
  File "/home/ilario/.venv/lib/python3.10/site-packages/summit/strategies/neldermead.py", line 457, in _inner_suggest_experiments
    overfull_simplex, _, _, _, _, _ = self.check_overfull(
  File "/home/ilario/.venv/lib/python3.10/site-packages/summit/strategies/neldermead.py", line 910, in check_overfull
    raise ValueError(
ValueError: Simplex is overfull in one dimension. Please increase threshold for stopping.
´´´

**Comment by ilario** [comment]
Thanks for the new example in #202!
Now the code runs, but the plotting complains about this:
```

>>> r.experiment.pareto_plot(ax=ax)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ax' is not defined. Did you mean: 'max'?
```

**Comment by ilario** [comment]
I suppose this has been fixed in e0b011198b2da3b135505c045c0599d9294e6068 (but I did not check), closing.
